package je.panse.doro.support.sqlite3_manager.labcode;

import java.sql.*;
import je.panse.doro.entry.EntryDir;

/**
 * A class to append simplified laboratory code data into an existing SQLite database
 * and manage duplicates.
 */
public class AddLabCodeDatabase {

    private static final String DB_URL = "jdbc:sqlite:" + EntryDir.homeDir + "/support/sqlite3_manager/labcode/LabCodeFullDis.db";

    /**
     * Appends simplified laboratory data to the 'labcodes' table and removes duplicates.
     */
    public static void appendData() {
        String insertSQL = "INSERT INTO labcodes (Category, B_code, Items, unit, comment) VALUES (?, ?, ?, ?, ?)";
        try (Connection conn = DriverManager.getConnection(DB_URL);
             PreparedStatement pstmt = conn.prepareStatement(insertSQL)) {
            addLabData(pstmt);
            System.out.println("Data appended successfully.");
        } catch (SQLException e) {
            System.err.println("Error appending data: " + e.getMessage());
        }
        removeDuplicates(); // Remove duplicates after appending data
    }

    /**
     * Adds the simplified laboratory dataset to the database.
     *
     * @param pstmt The PreparedStatement to execute the insertions.
     * @throws SQLException If an error occurs during data insertion.
     */
    private static void addLabData(PreparedStatement pstmt) throws SQLException {
        String[][] labData = {
            {"Chemistry", "D2280004Z", "Creatinine(Urine)", "mg/dL", "."},
            {"Chemistry", "D3002004Z", "Microalbumin", "μg/mL", "."},
            {"Chemistry", "D3002004Z,D2280004Z", "A/C ratio", "mg/g crea.", "."},
            {"Chemistry", "D1840004Z", "T.Protein", "g/dL", "."},
            {"Chemistry", "D1880004Z", "Albumin", "g/dL", "."},
            {"Chemistry", "D1830004Z", "T.Bilirubin", "mg/dL", "."},
            {"Chemistry", "D2300004Z", "BUN", "mg/dL", "."},
            {"Chemistry", "D2280004Z", "Creatinine", "mg/dL", "."},
            {"Chemistry", "", "GFR", "", "."},
            {"Chemistry", "D2310004Z", "Uric acid", "mg/dL", "."},
            {"Chemistry", "D1860004Z", "AST(sGOT)", "IU/L", "."},
            {"Chemistry", "D1850004Z", "ALT(sGPT)", "IU/L", "."},
            {"Chemistry", "D1870004Z", "ALP", "U/L", "."},
            {"Chemistry", "D1890004Z", "GGT(γ-GTP)", "IU/L", "."},
            {"Chemistry", "D2510054Z", "LDH", "U/L", "."},
            {"Chemistry", "D2510014Z", "CK,total(CPK)", "U/L", "."},
            {"Chemistry", "D3800024Z", "Amylase", "U/L", "."},
            {"Lipid Panel", "D2611004Z", "Cholesterol, total", "mg/dL", "."},
            {"Lipid Panel", "D2263004Z", "Triglyceride", "mg/dL", "."},
            {"Lipid Panel", "D2613004Z", "HDL-cholesterol", "mg/dL", "."},
            {"Lipid Panel", "D2614004Z", "LDL-cholesterol", "mg/dL", "."},
            {"Electrolytes", "D2800054Z", "Calcium (Ca)", "mg/dL", "."},
            {"Electrolytes", "D2800044Z", "Phosphorus (P)", "mg/dL", "."},
            {"Electrolytes", "D2800024Z", "Sodium (Na)", "mmol/L", "."},
            {"Electrolytes", "D2800034Z", "Chloride (Cl)", "mmol/L", "."},
            {"Electrolytes", "D2800064Z", "Potassium (K)", "mmol/L", "."},
            {"Iron Studies", "D0521034Z", "Iron (Fe)", "μg/dL", "."},
            {"Iron Studies", "D0521044Z", "TIBC", "μg/dL", "."},
            {"Glucose", "D3022004Z", "Glucose", "mg/dL", "."},
            {"Glucose", "D3063004Z", "HbA1C", "%", "."},
            {"Blood Type", "D1502004Z", "ABO혈액형(자동화)", "", "."},
            {"Blood Type", "D1512004Z", "Rh type(자동화)", "", "."},
            {"CBC", "D0002014Z", "WBC count", "천/㎕", "."},
            {"CBC", "D0002034Z", "RBC count", "백만/㎕", "."},
            {"CBC", "D0002054Z", "Hemoglobin", "g/㎗", "."},
            {"CBC", "D0002044Z", "Hematocrit", "%", "."},
            {"CBC", "", "MCV", "fL", "."},
            {"CBC", "", "MCH", "pg", "."},
            {"CBC", "", "MCHC", "g/㎗", "."},
            {"CBC", "D0002024Z", "RDW", "%", "."},
            {"CBC", "D0002074Z", "Platelet", "천/㎕", "."},
            {"CBC", "", "MPV", "fL", "."},
            {"CBC", "", "PCT", "%", "."},
            {"CBC", "D0002064Z", "PDW", "fL", "."},
            {"CBC", "D0013004Z", "Differential count (Lymphocyte)", "%", "."},
            {"CBC", "D0013004Z", "Differential count (Monocyte)", "%", "."},
            {"CBC", "D0013004Z", "Differential count (Neutrophil seg.)", "%", "."},
            {"CBC", "D0013004Z", "Differential count (Eosinophil)", "%", "."},
            {"CBC", "D0013004Z", "Differential count (Basophil)", "%", "."},
            {"CBC", "D0013004Z", "Differential count (Other)", "%", "."},
            {"CBC", "D0100014Z", "ESR", "mm/hrs", "."},
            {"Vitamins", "D4902024Z", "25-OH-Vit.D", "ng/mL", "."},
            {"Thyroid", "D3230044Z", "T4", "μg/dL", "."},
            {"Thyroid", "D3250014Z", "TSH", "mIU/L", "."},
            {"Tumor Markers", "D2420024Z", "AFP", "ng/mL", "."},
            {"Tumor Markers", "D4290004Z", "CEA", "ng/mL", "."},
            {"Tumor Markers", "D4350004Z", "CA19-9", "U/mL", "."},
            {"Tumor Markers", "D4300034Z", "PSA (total PSA)", "ng/mL", "."},
            {"Tumor Markers", "D4300014Z", "PSA, free", "ng/mL", "."},
            {"Tumor Markers", "", "Ratio (%)", "%", "."},
            {"Rheumatology", "D7811004Z", "RF 정성", "", "."},
            {"Rheumatology", "D0113004Z", "CRP 정량", "mg/dL", "."},
            {"Infectious Diseases", "D6913004Z", "RPR정밀", "R.U", "."},
            {"Infectious Diseases", "D7212004Z", "HIV Ag/Ab(Combo)", "COI", "."},
            {"Infectious Diseases", "D7011014Z", "HAV-Ab Total(IgG)", "mIU/mL", "."},
            {"Infectious Diseases", "D7015004Z", "HBsAg", "Index", "."},
            {"Infectious Diseases", "D7018004Z", "HBsAb", "mIU/mL", "."},
            {"Infectious Diseases", "D7005004Z", "HCV Ab(일반)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Specific gravity)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (PH)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Leukocytes)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Nitrite)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Proteins)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Glucose)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Ketones)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Urobilinogen)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Bilirubin)", "", "."},
            {"Urinalysis", "D2253004Z", "Urine 10종 (Blood)", "", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (WBC)", "/HPF", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (RBC)", "/HPF", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (Epithelial cells)", "/HPF", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (Bacteria)", "", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (Crystals)", "", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (Casts)", "", "."},
            {"Urinalysis", "D2201024Z", "요침사검사 (Others)", "", "."},
            {"Chemistry", "D1880000Z", "A/G ratio", "N/A", "."},
            {"Chemistry", "D1880000Z", "Albumin", "g/dL", "."},
            {"Chemistry", "D1880000Z", "Albumin (fluid)", "g/dL", "."},
            {"Chemistry", "D1920000Z", "Ammonia(NH3)", "μmol/L", "."},
            {"Chemistry", "D2300000Z,D2280000Z", "B/C ratio", "N/A", "."},
            {"Chemistry", "D1820000Z", "D.Bilirubin", "mg/dL", "."},
            {"Chemistry", "D1820000Z,D1830000Z", "I.Bilirubin", "mg/dL", "."},
            {"Chemistry", "D1830000Z", "T.Bilirubin", "mg/dL", "."},
            {"Chemistry", "D2300000Z", "BUN", "mg/dL", "."},
            {"Chemistry", "D2300000Z", "Urine Urea Nitrogen", "mg/24hr", "."},
            {"Chemistry", "D2280000Z", "Creatinine", "mg/dL", "."},
            {"Chemistry", "D2280000Z", "Creatinine(Urine)", "mg/24hr", "."},
            {"Chemistry", "D2321000Z", "Creatinine clearance(CCr)", "mL/min", "."},
            {"Chemistry", "D1880000Z,D1840000Z", "Globulin", "g/dL", "."},
            {"Chemistry", "D1840000Z", "T.Protein", "g/dL", "."},
            
            {"Chemistry", "D1840000Z", "Protein, total(Urine)", "mg/24hr", "."},
            {"Chemistry", "D2310000Z", "Uric acid", "mg/dL", "."},
            {"Chemistry", "D2310000Z", "Uric acid (Urine)", "mg/24hr", "."},
            {"Chemistry", "D2310000Z", "Uric acid (fluid)", "mg/dL", "."},
            {"Chemistry", "D2290000Z", "ACP (Acid phosphatase)", "U/L", "."},
            {"Chemistry", "D2530000Z", "ADA(Adenosine deaminase)", "U/L", "."},
            {"Chemistry", "D2290000Z", "ACP (Acid phosphatase)(Fluid)", "U/L", "."},
            {"Chemistry", "D2510080Z", "Aldolase", "U/L", "."},
            {"Chemistry", "D1870000Z", "ALP", "U/L", "."},
            {"Chemistry", "D1850000Z", "ALT(sGPT)", "U/L", "."},
            {"Chemistry", "D3800020Z", "Amylase", "U/L", "."},
            {"Chemistry", "D3800020Z", "Amylase (fluid)", "U/L", "."},
            {"Chemistry", "D1860000Z", "AST(sGOT)", "U/L", "."},
            {"Chemistry", "D2510090Z", "Cholinesterase", "U/L", "."},
            {"Chemistry", "D2510010Z", "CK, total(CPK)", "U/L", "."},
            {"Chemistry", "D4040000Z", "CK-MB", "ng/mL", "."},
            {"Chemistry", "D0550010Z", "G-6-PDH", "U/L", "."},
            {"Chemistry", "D1890000Z", "GGT(γ-GTP)", "U/L", "."},
            {"Chemistry", "D2510040Z", "LAP", "U/L", "."},
            {"Chemistry", "D2510050Z", "LDH", "U/L", "."},
            {"Chemistry", "D2510050Z", "LDH (fluid)", "U/L", "."},
            {"Chemistry", "D4023020Z", "Troponin-T hs", "ng/mL", "."},
            {"Chemistry", "D3800010Z", "Lipase", "U/L", "."},
            {"Chemistry", "D1870000Z", "ALP (fluid)", "U/L", "."},
            {"Chemistry", "D4023010Z", "Troponin-I", "ng/mL", "."},
            {"Chemistry", "", "Trypsin", "mg/dL", "."},
            {"Chemistry", "D2630020Z", "Apolipoprotein A-1", "mg/dL", "."},
            {"Chemistry", "D2630020Z", "Apolipoprotein A-2", "mg/dL", "."},
            {"Chemistry", "D2630030Z", "Apolipoprotein B", "mg/dL", "."},
            {"Chemistry", "D2630040Z", "Apolipoprotein C-2", "mg/dL", "."},
            {"Chemistry", "D2630040Z", "Apolipoprotein C-3", "mg/dL", "."},
            {"Chemistry", "D2630050Z", "Apolipoprotein E", "mg/dL", "."},
            {"Chemistry", "D2611000Z", "Cholesterol, total", "mg/dL", "."},
            {"Chemistry", "D2264000Z", "Free fatty acid (FFA)", "mEq/L", "."},
            {"Chemistry", "D2613000Z", "HDL-cholesterol", "mg/dL", "."},
            {"Chemistry", "D2614000Z", "LDL-cholesterol", "mg/dL", "."},
            {"Chemistry", "", "Leptin", "ng/mL", "."},
            {"Chemistry", "", "Lipopro lipase", "ng/mL", "."},
            {"Chemistry", "D2620000Z", "LP(a) (Lipoprotein a)", "mg/dL", "."},
            {"Chemistry", "D2261000Z", "Phospholipid", "mg/dL", "."},
            {"Chemistry", "D2263000Z", "Triglyceride", "mg/dL", "."},
            {"Chemistry", "D2630010Z", "β-Lipoprotein", "mg/dL", "."},
            {"Chemistry", "D3040000Z", "Fructosamine", "μmol/L", "."},
            {"Chemistry", "D3022000Z", "Glucose", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "Glucose (U)", "mg/24hr", "."},
              {"Chemistry", "D3022000Z", "Glucose tolerance(50g)", "mg/dL", "."},
            {"Chemistry", "D3063000Z", "HbA1C", "%", "."},
            {"Chemistry", "D2800050Z", "Calcium (Ca)", "mg/dL", "."},
            {"Chemistry", "D2800050Z", "Calcium (Urine)", "mg/24hr", "."},
            {"Chemistry", "D2800030Z", "Chloride (Cl)", "mmol/L", "."},
            {"Chemistry", "", "GFR", "mL/min", "."},
            {"Chemistry", "D2810020Z", "Ca++", "mmol/L", "."},
            {"Chemistry", "D2800010Z", "Magnesium (Mg)", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "GTT100g(임신성 당뇨)", "mg/dL", "."},
            {"Chemistry", "D2820000Z", "Osmolality", "mOsm/kg", "."},
            {"Chemistry", "D2800040Z", "Phosphorus (P)", "mg/dL", "."},
            {"Chemistry", "D2820000Z", "Osmolality (Urine)", "mOsm/kg", "."},
            {"Chemistry", "D2800060Z", "Potassium (K)", "mmol/L", "."},
            {"Chemistry", "D2263000Z", "TG(Fluid)", "mg/dL", "."},
            {"Chemistry", "D2800020Z", "Sodium (Na)", "mmol/L", "."},
            {"Chemistry", "D2800030Z", "Cl (Urine)", "mmol/24hr", "."},
            {"Chemistry", "D2800010Z", "Magnesium (U)", "mg/24hr", "."},
            {"Chemistry", "D0521030Z", "Iron (Fe)", "μg/dL", "."},
            {"Chemistry", "D2800040Z", "P (Urine)", "mg/24hr", "."},
            {"Chemistry", "D1840000Z,D2280000Z", "P/C Ratio", "N/A", "."},
            {"Chemistry", "D4012000Z", "Myoglobin", "ng/mL", "."},
            {"Chemistry", "D4012000Z", "Myoglobin (U)", "ng/mL", "."},
            {"Chemistry", "", "Retinol binding protein(RBP)", "mg/L", "."},
            {"Chemistry", "D0521040Z", "TIBC", "μg/dL", "."},
            {"Chemistry", "D0521040Z,D0521030Z", "Transferrin saturation", "%", "."},
            {"Chemistry", "D0521010Z", "UIBC", "μg/dL", "."},
            {"Chemistry", "D5145006Z,D5146046Z,D5146036Z", "Amino acid", "μmol/L", "."},
            {"Chemistry", "D5151020Z", "Citric acid (U)", "mg/24hr", "."},
            {"Chemistry", "D5147010Z", "Homocysteine, total(mass)", "μmol/L", "."},
            {"Chemistry", "", "Homogentistic acid (HGA)", "mg/L", "."},
              {"Chemistry", "", "Hyaluronic acid", "ng/mL", "."},
            {"Chemistry", "CZ244", "Hydroxyproline, total", "mg/24hr", "."},
            {"Chemistry", "D3011000Z", "Ketone 정성", "N/A", "."},
            {"Chemistry", "D3013006Z", "Ketone body 3분획", "mmol/L", "."},
            {"Chemistry", "D5110000Z", "Lactic acid", "mmol/L", "."},
            {"Chemistry", "D5153016Z", "Methylmalonic acid 정량", "μmol/L", "."},
            {"Chemistry", "D2260000Z", "NAG", "U/g Cr", "."},
            {"Chemistry", "D5154006Z", "Organic acids", "mmol/L", "."},
            {"Chemistry", "D5153026Z", "Oxalic acid(Oxalate)", "mg/24hr", "."},
            {"Chemistry", "D5151030Z", "Pyruvic acid", "mmol/L", "."},
            {"Chemistry", "", "Sialic acid(Sialate)", "mg/L", "."},
            {"Chemistry", "D1900000Z", "Bile acid, total", "μmol/L", "."},
            {"Chemistry", "D5349866Z", "Teicoplanin", "μg/mL", "."},
            {"Chemistry", "D5162000Z", "Coproporphyrin", "μg/24hr", "."},
            {"Chemistry", "D5161000Z", "Coproporphyrin", "μg/g Cr", "."},
            
            {"Chemistry", "D5161000Z", "Porphyrin 정성", "N/A", "."},
            {"Chemistry", "D5163000Z", "Porphobilinogen정량", "μmol/24hr", "."},
            {"Chemistry", "D5161000Z", "Porphobilinogen정성", "N/A", "."},
            {"Chemistry", "D5161000Z", "Uroporphy정성", "N/A", "."},
            {"Chemistry", "D5333010Z", "Acetaminophen", "μg/mL", "."},
            {"Chemistry", "D5333020Z", "Amikacin", "μg/mL", "."},
            {"Chemistry", "D5333080Z", "Carbamazepine", "μg/mL", "."},
            {"Chemistry", "D5349206Z", "Clonazepam", "ng/mL", "."},
            {"Chemistry", "D5333110Z", "Cyclosporine", "ng/mL", "."},
            {"Chemistry", "", "Digitoxin", "ng/mL", "."},
            {"Chemistry", "D5333150Z", "Digoxin", "ng/mL", "."},
            {"Chemistry", "", "Disopyramide", "ng/mL", "."},
            {"Chemistry", "D5333420Z", "FK 506(Tacrolimus)", "ng/mL", "."},
            {"Chemistry", "", "Histamine", "ng/mL", "."},
            {"Chemistry", "D5349386Z", "Imipramine + Desipramine", "ng/mL", "."},

            {"Chemistry", "", "Lidocain", "ng/mL", "."},
            {"Chemistry", "D5333280Z", "Methotrexate(MTX)", "ng/mL", "."},
            {"Chemistry", "", "Cotinine(정성)", "N/A", "."},
            {"Chemistry", "", "Nicotine metabolite(정량)", "ng/mL", "."},
            {"Chemistry", "", "Nitrazepam", "ng/mL", "."},
            {"Chemistry", "D5343590Z", "Paraquat", "ng/mL", "."},
            {"Chemistry", "", "Nicotine(정성)", "N/A", "."},
            {"Chemistry", "D5333340Z", "Phenobarbital", "μg/mL", "."},
            {"Chemistry", "D5333360Z", "Phenytoin", "μg/mL", "."},
            {"Chemistry", "", "Procainamide", "ng/mL", "."},
            {"Chemistry", "", "Propranolol", "ng/mL", "."},
            {"Chemistry", "D5323400Z", "Salicylate(Aspirin)", "mg/L", "."},
            {"Chemistry", "D5333430Z", "Theophylline", "μg/mL", "."},
            {"Chemistry", "D5333450Z", "Valproic acid", "μg/mL", "."},
            {"Chemistry", "D5333470Z", "Vancomycin", "μg/mL", "."},
              {"Chemistry", "D5349996Z", "Zonisamide", "ng/mL", "."},
            {"Chemistry", "", "Amphetamine", "N/A", "."},
            {"Chemistry", "D5331040Z", "Barbiturate", "N/A", "."},
            {"Chemistry", "D5321050Z", "Benzodiazepin", "N/A", "."},
            {"Chemistry", "", "Cannabinoid(Marihuana) 정성", "N/A", "."},
            {"Chemistry", "", "Cocaine", "N/A", "."},
            {"Chemistry", "", "Morphine", "N/A", "."},
            {"Chemistry", "", "Phencyclidine", "N/A", "."},
            {"Chemistry", "", "TBPE 정성", "N/A", "."},
            {"Chemistry", "", "Opiates 정성", "N/A", "."},
            {"Chemistry", "", "MDMA(Ecstasy)", "N/A", "."},
            {"Chemistry", "D4902140Z", "Folate", "ng/mL", "."},
            {"Chemistry", "D4904020Z", "Vitamin A(Retinol)", "μg/dL", "."},
            {"Chemistry", "D4904036Z", "Vitamin B1(Thiamine)", "ng/mL", "."},
            {"Chemistry", "D4904046Z", "Vitamin B2", "ng/mL", "."},
            {"Chemistry", "D4904056Z", "Vitamin B6", "ng/mL", "."},
            {"Chemistry", "D4902050Z", "Vitamin B12(Cyanocobalamine)", "pg/mL", "."},
            {"Chemistry", "D4904120Z", "Vitamin BT", "ng/mL", "."},
            {"Chemistry", "D4904066Z", "Vitamin C", "mg/L", "."},
            {"Chemistry", "", "Vitamin E Fraction", "mg/L", "."},
            {"Chemistry", "D4904096Z", "Vitamin E(α-tocopherol)", "mg/L", "."},
            {"Chemistry", "D5171056Z", "Arylsulfatase A", "U/L", "."},
            {"Chemistry", "", "Heparin", "U/mL", "."},
            {"Chemistry", "D5511020Z", "Aluminium(Al)", "μg/L", "."},
            {"Chemistry", "D3800030Z", "Pancreatic Amylase", "U/L", "."},
            {"Chemistry", "D5511030Z", "Arsenic(As)", "μg/L", "."},
            {"Chemistry", "D5511020Z", "Aluminium (U)", "μg/24hr", "."},
            {"Chemistry", "D5511040Z", "Cadmium(Cd)", "μg/L", "."},
            {"Chemistry", "D5511040Z", "Cadmium (U)", "μg/24hr", "."},
            {"Chemistry", "D5511060Z", "Chromium(Cr)", "μg/L", "."},
            {"Chemistry", "D5511060Z", "Chromium(Cr)(U)", "μg/24hr", "."},
            {"Chemistry", "D5511050Z", "Cobalt(Co)", "μg/L", "."},
            {"Chemistry", "D5511050Z", "Cobalt(Co)(Urine)", "μg/24hr", "."},
            {"Chemistry", "D5511070Z", "Copper(Cu)", "μg/dL", "."},
            {"Chemistry", "D5511070Z", "Copper(Cu)(Urine)", "μg/24hr", "."},
            {"Chemistry", "D5511150Z", "Lead(Pb)", "μg/dL", "."},
            {"Chemistry", "D5511150Z", "Lead (U)", "μg/24hr", "."},
            {"Chemistry", "D5503100Z", "Lithium(Li)", "mmol/L", "."},
            {"Chemistry", "D5511130Z", "Mn", "μg/L", "."},
            {"Chemistry", "D5511100Z", "Mercury(Hg)", "μg/L", "."},
            {"Chemistry", "D5511100Z", "Mercury(Hg) (U)", "μg/24hr", "."},
            {"Chemistry", "D5511140Z", "Nickel(Ni)", "μg/L", "."},
            {"Chemistry", "", "혈중 중금속 및 미네랄 13종 검사", "N/A", "."},
            {"Chemistry", "D5511170Z", "Selenium(Se)", "μg/L", "."},
            {"Chemistry", "D5349216Z", "Clozapine/Norclozapine", "ng/mL", "."},
            {"Chemistry", "D5511180Z", "Zinc(Zn)", "μg/dL", "."},
            {"Chemistry", "D5511180Z", "Zinc(Zn)(Urine)", "μg/24hr", "."},
            {"Chemistry", "CZ191", "Iodine(24hr urine)", "μg/24hr", "."},
            {"Chemistry", "D5323180Z", "Alcohol", "mg/dL", "."},
            {"Chemistry", "D5423140Z", "Phenol", "mg/L", "."},
            {"Chemistry", "CZ430", "AIT 정량(Autoimmune Target Test)", "N/A", "."},
            {"Chemistry", "D4902140Z", "RBC Folate", "ng/mL", "."},
            {"Chemistry", "", "유기산정량분석검사(OAP)", "N/A", "."},
            {"Chemistry", "", "혈중 중금속4종 검사", "N/A", "."},
            {"Chemistry", "D5323180Z", "Alcohol(Urine)", "mg/dL", "."},
            {"Chemistry", "D5349046Z", "Amiodarone", "ng/mL", "."},
            {"Chemistry", "D3513010Z", "5-HIAA 정량 (RU)", "mg/24hr", "."},
            {"Chemistry", "D2612000Z", "Ester Cholesterol", "mg/dL", "."},
            {"Chemistry", "D5349326Z", "Everolimus", "ng/mL", "."},
            {"Chemistry", "D2611000Z,D2613000Z", "CRF", "N/A", "."},
            {"Chemistry", "D2800020Z외", "Anion GAP", "mmol/L", "."},
            {"Chemistry", "D3504016Z", "11-Deoxycorticosterone", "ng/mL", "."},
            {"Chemistry", "D3022000Z*3", "GTT (75g)", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "Glucose(pp2)", "mg/dL", "."},
            {"Chemistry", "D5333190Z", "Gentamicin", "μg/mL", "."},
            {"Chemistry", "D0301026Z", "Stone Analysis", "N/A", "."},
            {"Chemistry", "D3022000Z", "Glucose(PP1)", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "Glucose(PP3)", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "Glucose(FBS)", "mg/dL", "."},
            {"Chemistry", "D3022000Z", "Glucose (fluid)", "mg/dL", "."},
            {"Chemistry", "D5010010Z", "CTx", "ng/mL", "."},
            {"Chemistry", "D5000010Z", "Bone ALP", "U/L", "."},
            {"Chemistry", "D2330000Z", "Cystatin-C", "mg/L", "."},
            {"Chemistry", "D3013006Z", "Ketone body 3분획", "mmol/L", "."},
            {"Chemistry", "D5349746Z", "Quetiapine", "ng/mL", "."},
            {"Chemistry", "D5349616Z", "Oxcarbazepine & Metabolite", "ng/mL", "."},
            {"Chemistry", "D0521020Z", "Zn protoporphyrin", "μg/dL", "."},
            {"Chemistry", "D2342000Z", "NGAL, quantitative test", "ng/mL", "."},
            {"Chemistry", "", "소변 중금속 및 미네랄 검사", "N/A", "."},
            {"Chemistry", "", "혈액중금속 4종Ⅰ(As,Pb,Hg,Cd)", "N/A", "."},
            {"Chemistry", "", "혈액중금속 4종 Ⅱ(Al,Pb,Hg,Cd)", "N/A", "."},
            {"Chemistry", "", "Blood trace elements profile", "N/A", "."},
            {"Chemistry", "D5503090Z,D2280000Z", "Iodine/Cr ratio", "N/A", "."},
            {"Chemistry", "D0160000Z", "KL-6", "U/mL", "."},
            {"Chemistry", "D3002000Z,D2280000Z", "A/C ratio", "N/A", "."},
            {"Chemistry", "D2830000Z", "Total CO2", "mmol/L", "."},
            {"Chemistry", "D3050020Z,D3022000Z", "HOMA of insulin resistance", "N/A", "."},
            {"Chemistry", "D3050020Z,D3022000Z", "HOMA β-cell", "N/A", "."},
            {"Chemistry", "", "Heroin", "N/A", "."},
            {"Chemistry", "D3002000Z", "Albumin (CSF)", "mg/dL", "."},
            {"Chemistry", "", "Beta-Carotene", "μg/dL", "."},
            {"Chemistry", "", "내분비 교란물질 Ⅰ", "N/A", "."},
            {"Chemistry", "", "내분비 교란물질 Ⅱ", "N/A", "."},
            {"Chemistry", "", "내분비 교란물질 Ⅲ", "N/A", "."},
            {"Chemistry", "", "환경성 독성물질Ⅰ", "N/A", "."},
            {"Chemistry", "", "CM-LDL cholesterol", "mg/dL", "."},
            {"Chemistry", "D5349A16Z", "Delta-ALA", "μmol/L", "."},
            {"Chemistry", "D1980000Z", "M2BPGi", "ng/mL", "."},
            {"Chemistry", "", "1CTP(type I collagen)", "ng/mL", "."},
            {"Chemistry", "D3501040Z", "17-Ketosteroid", "mg/24hr", "."},
            {"Chemistry", "D3501050Z", "17-OHCS", "mg/24hr", "."},
            {"Chemistry", "D2520000Z", "ACE", "U/L", "."},
            {"Chemistry", "D3514016Z", "5-HIAA 정량", "mg/24hr", "."},
            {"Chemistry", "D3511010Z", "5-HIAA 정성", "N/A", "."},
            {"Chemistry", "D3514086Z,D3514056Z", "Catecholamine(P)2분획", "nmol/L", "."},
            {"Chemistry", "D3514086Z,D3514056Z,D3514026Z", "Catecholamine(P)3분획", "nmol/L", "."},
            {"Chemistry", "D3514086Z,D3514056Z", "Catecholamine(U)2분획", "nmol/24hr", "."},
            {"Chemistry", "D3514086Z,D3514056Z,D3514026Z", "Catecholamine(U)3분획", "nmol/24hr", "."},
            {"Chemistry", "D3514036Z", "HVA (Urine)", "mg/24hr", "."},
            {"Chemistry", "", "L-Dopa", "ng/mL", "."},
            {"Chemistry", "", "Lysozyme", "mg/L", "."},
            {"Chemistry", "D3514046Z,D3514066Z", "Metanephrine 2분획", "nmol/L", "."},
            {"Chemistry", "", "Methamphetamine", "N/A", "."},
            {"Chemistry", "", "P2", "mg/24hr", "."},
            {"Chemistry", "D4270000Z*2", "Pepsinogen I/II", "ng/mL", "."},
            {"Chemistry", "D4904086Z", "25-OH Vitamin D2 & D3", "ng/mL", "."},
            {"Chemistry", "D4700020Z", "α1-Antitrypsin", "mg/dL", "."},
            {"Chemistry", "", "VMA정량(EDTA)", "mg/24hr", "."},
            {"Chemistry", "CZ112000Z", "CDT", "N/A", "."},
            {"Chemistry", "", "Paraoxonase(PON1)", "U/L", "."},
            {"Chemistry", "D3514016Z", "5-HIAA 정량(Plasma)", "nmol/L", "."},
            {"Chemistry", "D0113000Z", "CRP정량(Fluid)", "mg/L", "."},
            {"Chemistry", "D7471010Z", "C3", "mg/dL", "."},
            {"Chemistry", "D7471020Z", "C4", "mg/dL", "."},
            {"Chemistry", "D4700010Z", "Ceruloplasmin", "mg/dL", "."},
            {"Chemistry", "D7400000Z", "CH50", "U/mL", "."},
            {"Chemistry", "D0113000Z", "CRP 정량", "mg/L", "."},
            {"Chemistry", "D0111000Z", "CRP 정성", "N/A", "."},
            {"Chemistry", "D0113000Z", "high-sensitivity CRP", "mg/L", "."},
            {"Chemistry", "D7410010Z", "IgA", "mg/dL", "."},
            {"Chemistry", "D7410040Z", "IgG", "mg/dL", "."},
            {"Chemistry", "D7410050Z", "IgM", "mg/dL", "."},
            {"Chemistry", "D4710020Z", "Prealbumin", "mg/dL", "."},
            {"Chemistry", "D7813000Z", "RF 정량", "IU/mL", "."},
            {"Chemistry", "D7811000Z", "RF 정성", "N/A", "."},
            {"Chemistry", "D4710010Z", "Transferrin", "mg/dL", "."},
            {"Chemistry", "D5833000Z", "ASO 정량", "IU/mL", "."},
            {"Chemistry", "D5831000Z", "ASO 정성", "N/A", "."},
            {"Chemistry", "D6911000Z", "RPR 정성", "N/A", "."},
            {"Chemistry", "D6923000Z", "TPLA(정밀)", "N/A", "."},
            {"Chemistry", "D6913000Z", "RPR정밀", "N/A", "."},
            {"Chemistry", "D6911000Z", "VDRL 정성(CSF)", "N/A", "."},
            {"Chemistry", "", "Human amyloid β", "pg/mL", "."},
            {"Chemistry", "", "모발분석", "N/A", "."},
            {"Chemistry", "D6912000Z", "VDRL 정량(CSF)", "N/A", "."},
            {"Chemistry", "", "E3(Estriol)", "ng/mL", "."},
            {"Chemistry", "D1860000Z,D1850000Z,D0002070Z", "Fibrosis-4", "N/A", "."},
            {"Chemistry", "D5349446Z", "Levetiracetam", "ng/mL", "."},
            {"Chemistry", "D5349906Z", "Topiramate", "ng/mL", "."},
            {"Chemistry", "D5349636Z", "Paroxetine", "ng/mL", "."},
            {"Chemistry", "D3022", "Glucose", "mg/dL", "."},
            {"Chemistry", "D2611", "Cholesterol, total", "mg/dL", "."},
            {"Chemistry", "D2613", "HDL-cholesterol", "mg/dL", "."},
            {"Chemistry", "D2263", "Triglyceride", "mg/dL", "."},
            {"Chemistry", "D2614", "LDL-cholesterol", "mg/dL", "."},
            {"Chemistry", "D1860", "AST(sGOT)", "U/L", "."},
            {"Chemistry", "D1850", "ALT(sGPT)", "U/L", "."},
            {"Chemistry", "D1890", "GGT(γ-GTP)", "U/L", "."},
            {"Chemistry", "D2280", "Creatinine", "mg/dL", "."},
            {"Chemistry", "", "LDL-cholesterol(계산법)", "mg/dL", "."},
            {"Chemistry", "", "GFR", "mL/min", "."},
            {"Hematology", "D0521020Z", "Zn protoporphyrin", "μg/dL", "."},
            {"Hematology", "D5310000Z", "Dyshemoglobin Test", "N/A", "."},
            {"Hematology", "D1541056Z,D1561006Z,D1562006Z", "Ab Identification Test 외", "N/A", "."},
            {"Hematology", "D1561006Z", "Ab Screening Test", "N/A", "."},
            {"Hematology", "C5806", "ABO genotyping", "N/A", "."},
            {"Hematology", "D0831000Z", "Bone Marrow Exa", "N/A", "."},
            {"Hematology", "D1541056Z", "Coombs direct", "N/A", "."},
            {"Hematology", "D1542056Z", "Coombs indirect", "N/A", "."},
            {"Hematology", "D0013000Z", "Differential count", "N/A", "."},
            {"Hematology", "D1514000Z", "Du test", "N/A", "."},
            {"Hematology", "D0022000Z", "Eosinophil count", "cells/μL", "."},
            {"Hematology", "D0100010Z", "ESR", "mm/hr", "."},
            {"Hematology", "D0510006Z", "P.B Cell Morphology (PBS)", "N/A", "."},
            {"Hematology", "D0502010Z", "Reticulocyte count", "%", "."},
            {"Hematology", "D1570006Z", "Rh Ab Titer", "N/A", "."},
            {"Hematology", "D1513006Z", "Rh-Hr Subgroup", "N/A", "."},
            {"Hematology", "D5300030Z", "CO-Hb", "%", "."},
            {"Hematology", "", "Fetal Hb", "%", "."},
            {"Hematology", "D0531016Z", "Ham^s test", "N/A", "."},
            {"Hematology", "D0841016Z", "LAP score", "N/A", "."},
            {"Hematology", "D7800006Z", "LE cell", "N/A", "."},
            {"Hematology", "D6409006Z", "Malaria, Filaria", "N/A", "."},
            {"Hematology", "D5300010Z", "Met Hb", "%", "."},
            {"Hematology", "D1004000Z", "APTT", "sec", "."},
            {"Hematology", "D1121000Z", "Antithrombin Ⅲ", "%", "."},
            {"Hematology", "D1073000Z", "D-dimer 정량", "ng/mL", "."},
            {"Hematology", "D1131016Z", "Factor II(2)", "%", "."},
            {"Hematology", "D1131026Z", "Factor Ⅴ(5)", "%", "."},
            {"Hematology", "D1131036Z", "Factor Ⅶ(7)", "%", "."},
            {"Hematology", "D1131046Z", "Factor Ⅷ(8)", "%", "."},
            {"Hematology", "D1040016Z", "Factor Ⅷ(8) Ab", "N/A", "."},
            {"Hematology", "D1131056Z", "Factor Ⅸ(9)", "%", "."},
            {"Hematology", "D1040026Z", "Factor Ⅸ(9) Ab", "N/A", "."},
            {"Hematology", "D1131066Z", "Factor Ⅹ(10)", "%", "."},
            {"Hematology", "D1131076Z", "Factor XI(11)", "%", "."},
            {"Hematology", "D1131086Z", "Factor XII(12)", "%", "."},
            {"Hematology", "D1131096Z", "Factor XIII(13)", "%", "."},
            {"Hematology", "D1005000Z", "Fibrinogen(Factor1)", "mg/dL", "."},
            {"Hematology", "D1112006Z", "Lupus Anticoagulant (confirm)", "N/A", "."},
            {"Hematology", "D1261000Z", "Plasminogen", "%", "."},
            {"Hematology", "D1272000Z", "PA inhibitor-1", "U/mL", "."},
            {"Hematology", "D1141000Z", "Protein C activity", "%", "."},
            {"Hematology", "D1142000Z", "Protein C Ag", "mg/dL", "."},
            {"Hematology", "D1151000Z", "Protein S activity", "%", "."},
            {"Hematology", "D1152000Z", "Protein S Ag", "mg/dL", "."},
            {"Hematology", "D1152000Z", "Protein S, free", "mg/dL", "."},
            {"Hematology", "D1003000Z", "PT", "sec", "."},
            {"Hematology", "D1006000Z", "Thrombin time", "sec", "."},
            {"Hematology", "D2110000Z", "vWF(Ristocetin Cofactor)", "%", "."},
            {"Hematology", "D2111000Z", "vWF Ag", "mg/dL", "."},
            {"Hematology", "D1030026Z", "Plasma Mixing Test", "N/A", "."},
            {"Hematology", "D1083000Z", "FDP(TIA)", "ng/mL", "."},
            {"Hematology", "D0590000Z", "Plasma Hb", "mg/dL", "."},
            {"Hematology", "D6431000Z", "Rapid Malaria Test", "N/A", "."},
            {"Hematology", "D1030030Z", "APCR", "N/A", "."},
            {"Hematology", "CZ250", "혈액점도검사(Scanning 모세관법)", "N/A", "."},
            {"Hematology", "D1111000Z", "Lupus Anticoagulant (screen)", "N/A", "."},
            {"Hematology", "D0502020Z", "Unmatured Reticulocyte Fractionation", "%", "."},
            {"Hematology", "D1551006Z", "RHD genotype screening [PCR]", "N/A", "."},
            {"Hematology", "D1552006Z", "RHD genotype identification [Sequencing]", "N/A", "."},
            {"Hematology", "", "ABO subgroup sequencing", "N/A", "."},
            {"Hematology", "D1550000Z", "Cross matching", "N/A", "."},
            {"Hematology", "C5801056Z", "Factor V Leiden R534Q Mutation", "N/A", "."},
            {"Hematology", "C5801046Z", "PT G20210A Mutation", "N/A", "."},
            {"Hematology", "D0002010Z", "WBC count", "cells/μL", "."},
            {"Hematology", "D0002030Z", "RBC count", "cells/μL", "."},
            {"Hematology", "D0002050Z", "Hemoglobin", "g/dL", "."},
            {"Hematology", "D0002040Z", "Hematocrit", "%", "."},
            {"Hematology", "", "MCV", "fL", "."},
            {"Hematology", "", "MCH", "pg", "."},
            {"Hematology", "", "MCHC", "g/dL", "."},
            {"Hematology", "D0002070Z", "Platelet", "cells/μL", "."},
            {"Hematology", "D0002020Z", "RDW", "%", "."},
            {"Hematology", "", "PCT", "%", "."},
            {"Hematology", "", "MPV", "fL", "."},
            {"Hematology", "D0002060Z", "PDW", "%", "."},
            {"Hematology", "D0325000Z", "Eosinophil count(Others)", "cells/μL", "."},
            {"Hematology", "D0002010Z,D0013000Z", "Absolute Neutrophil count(ANC)", "cells/μL", "."},
            {"Hematology", "D1570006Z", "Rh Ab Titer", "N/A", "."},
            {"Hematology", "D1501000Z", "ABO혈액형(Capillary)", "N/A", "."},
            {"Hematology", "D1511000Z", "Rh type(Capillary)", "N/A", "."},
            {"Hematology", "D1502000Z", "ABO혈액형(자동화)", "N/A", "."},
            {"Hematology", "D1512000Z", "Rh type(자동화)", "N/A", "."},
            {"Hematology", "D0013000Z", "WBC Diff Count 6종", "N/A", "."},
            {"Hematology", "D0013000Z", "Differential count", "N/A", "."},
            {"Hematology", "D0013000Z", "WBC Diff. Count 14종", "N/A", "."},
            {"Body Fluid", "D0327000Z", "Body fluid analysis", "N/A", "."},
            {"Hematology", "D0002010Z외", "CBC 5종", "N/A", "."},
            {"Hematology", "D0002010Z외", "CBC 8종", "N/A", "."},
            {"Hematology", "D0002050", "Hemoglobin", "g/dL", "."}
        };

        for (String[] row : labData) {
            addRow(pstmt, row[0], row[1], row[2], row[3], row[4]);
        }
    }

    /**
     * Inserts a single row into the 'labcodes' table.
     *
     * @param pstmt    The PreparedStatement to execute the insertion.
     * @param category The category of the lab test (e.g., "Chemistry").
     * @param bCode    The insurance code (e.g., "D2280004Z").
     * @param items    The specific test item (e.g., "Creatinine(Urine)").
     * @param unit     The unit of measurement (e.g., "mg/dL").
     * @param comment  A placeholder comment (e.g., ".").
     * @throws SQLException If an error occurs during insertion.
     */
    private static void addRow(PreparedStatement pstmt, String category, String bCode, String items, String unit, String comment) throws SQLException {
        pstmt.setString(1, category);
        pstmt.setString(2, bCode);
        pstmt.setString(3, items);
        pstmt.setString(4, unit);
        pstmt.setString(5, comment);
        pstmt.executeUpdate();
    }

    /**
     * Removes duplicate entries from the 'labcodes' table based on the 'Items' column.
     * Keeps the first occurrence of each unique 'Items' value.
     */
    public static void removeDuplicates() {
        try (Connection conn = DriverManager.getConnection(DB_URL);
             Statement stmt = conn.createStatement()) {

            // Create a temporary table for unique records
            stmt.execute("CREATE TABLE temp_labcodes (" +
                    "Category TEXT, " +
                    "B_code TEXT, " +
                    "Items TEXT, " +
                    "unit TEXT, " +
                    "comment TEXT" +
                    ");");

            // Insert unique records into the temporary table
            stmt.execute("INSERT INTO temp_labcodes (Category, B_code, Items, unit, comment) " +
                    "SELECT Category, B_code, Items, unit, comment " +
                    "FROM labcodes " +
                    "WHERE rowid IN (" +
                    "    SELECT MIN(rowid) " +
                    "    FROM labcodes " +
                    "    GROUP BY Items" +
                    ");");

            // Drop the original table and rename the temporary table
            stmt.execute("DROP TABLE IF EXISTS labcodes;");
            stmt.execute("ALTER TABLE temp_labcodes RENAME TO labcodes;");

            System.out.println("Duplicates removed successfully.");
        } catch (SQLException e) {
            System.err.println("Error removing duplicates: " + e.getMessage());
        }
    }

    /**
     * Main method to append the simplified laboratory data to the database and remove duplicates.
     *
     * @param args Command-line arguments (not used).
     */
    public static void main(String[] args) {
        appendData();
    }
}